codecov:
  token: e1d06778-12ae-4871-a587-cd98f04f5e7c
    notify:
      require_ci_to_pass: yes

  coverage:
    precision: 2
    round: down
    range: "85...100"

    status:
      project: yes
      patch: yes
      changes: no

  parsers:
    gcov:
      branch_detection:
        conditional: yes
        loop: yes
        method: no
        macro: no

  comment:
    layout: "header, diff"
    behavior: default
    require_changes: no


