codecov:
  token: 393a1f2f-b254-4a70-b6c1-747c729ab0e3
    notify:
      require_ci_to_pass: yes

  coverage:
    precision: 2
    round: down
    range: "85...100"

    status:
      project: yes
      patch: yes
      changes: no

  parsers:
    gcov:
      branch_detection:
        conditional: yes
        loop: yes
        method: no
        macro: no

  comment:
    layout: "header, diff"
    behavior: default
    require_changes: no


