spring:
  data:
    mongodb:
      host: ${mongo_ip:52.67.72.229}
      port: 27017
      database: album-sales-cashback
      repositories:
        enabled: true
  cache:
    type: redis
  redis:
    host: ${redis_host:52.67.72.229}
    port: ${redis_port:6379}
spotify:
  api:
    authorization:
      grant-type: client_credentials
      address: https://accounts.spotify.com/api/
      token:
        basic: N2M2MWQ5ODUzMzFiNDkxZWJiNjk4NjgxOWZiMDJmOTA6MGNiNGMyNzljMWY1NDM2NjhiZTUxNTY5ZWU5MThlNjE=
    search:
      address: https://api.spotify.com/v1/
cashback:
  genre:
    pop: "{SUNDAY: '25', MONDAY: '7', TUESDAY: '6', WEDNESDAY:'2', THURSDAY: '10', FRIDAY: '15', SATURDAY: '20'}"
    mpb: "{SUNDAY:'30', MONDAY:'5', TUESDAY:'10', WEDNESDAY:'15', THURSDAY: '20', FRIDAY: '25', SATURDAY: '30'}"
    classic: "{SUNDAY:'35', MONDAY:'3', TUESDAY:'5', WEDNESDAY:'8', THURSDAY: '13', FRIDAY: '18', SATURDAY: '25'}"
    rock: "{SUNDAY:'40', MONDAY:'10', TUESDAY:'15', WEDNESDAY:'15', THURSDAY: '15', FRIDAY: '20', SATURDAY: '40'}"

